#!/bin/sh

pkg_check() {
    name="$1"

    if ! echo $name | grep -q "\b${ext}\b$"; then
        err="The extension must be ${ext}"
        return 1
    fi

    if echo $name | grep -qE "\s+"; then
        err='The package name must not have spaces'
        return 1
    fi
    
    name_exp=$(basename $PWD)

    if ! echo $name | grep -qE "^${name_exp}-"; then
        err="The name of package must be $name_exp"
        return 1
    fi

    if ! echo $name | grep -qE "^[a-zA-Z0-9-]+-[0-9]+(\.[0-9]+)*-[0-9]+(\.[0-9]+)*\.${ext}$"; then
        err="The format expected is: Name-Version-Build.${ext}"
        return 1;
    fi

    return 0
}

pkg_create() {
    name=$1
    
    if tar cf$2 ../${name} .; then
        out="Package created in ../${name}"
        return 0
    fi        
    out="Error while creating package"
    return 1
}

