#!/bin/sh

Dir="$config/desc"

make_desc() {
    if [ ! -d "$Dir" ]; then
        mkdir -pv "./$Dir"
    fi        
    
    File=$(basename $PWD)
    cat <<EOF > "./${Dir}/${File}"
MAINTAINER=''
PACKAGE=''
ARCHITECTURE=''
DESCRIPTION=''
LICENSE=''
VERSION=''
URL=''
EOF

}

show_desc() {
    pakg="$1"
    File=$(echo "$pakg" | sed 's/-.*//')
    File=$(basename $File)
    dirtmp=$(mktemp -d)

    if tar -tf "${pakg}" ".${Dir}/${File}" >/dev/null 2>/dev/null; then
        if tar -xf "${pakg}" -C "${dirtmp}" ".${Dir}/${File}"; then
            . "${dirtmp}${Dir}/${File}"
            echo "Mainteiner  : $MAINTAINER"
            echo "Package     : $PACKAGE"
            echo "Architecture: $ARCHITECTURE"
            echo "Description : $DESCRIPTION"
            echo "License     : $LICENSE"
            echo "Version     : $VERSION"
            echo "Url         : $URL"
        fi            
    else
        echo 'Empty description' 
    fi

    [ -e "$dirtmp" ] && { rm -r "$dirtmp"; }
}

show_progs() {
    if ! cd "$config/installed"; then
        return 1
    fi
    
    nfiles=$(ls -A . 2>/dev/null | wc -l)
    
    if [ "$nfiles" != "0" ]; then
        for prog in *; do
            progname="${prog%.$ext}"
            echo "$progname"
        done
    fi

    echo "Total: $nfiles"

    return 0
}

