#!/bin/sh

track="$config/installed"
[ ! -d "$track" ] && mkdir -pv "$track"

install() {
    path_pkg="$1"
    dest="$2"
    mkdir -p "${dest}${track}" 2>/dev/null
    npkg=$(basename $path_pkg)
    npkg=$(echo "$npkg" | sed 's/\.rock//')
 
    if ! tar xvf "$pkg" -C "$dest/" >> "${dest}${track}/${pkg}" 2>/dev/null; then
        return 1
    fi
    
    sed -i 's/\.\//\//g; /^$/d; /^\/$/d' "${dest}${track}/${pkg}" 2>/dev/null

    return 0
}


