#!/bin/sh

export ext='rock'
export LC_ALL='C'
export LANG='C'

destdir=/home/wanderson/rockpkg
. "$destdir"/help
. "$destdir"/create
. "$destdir"/install

if [ -z $1 ]; then
    usage
fi

get_opt() {
    op="$1"
    case $op in
        --create|-c|--info|-I)
            cmd="$op"; shift
    ;;
        --install|-i)
            cmd="i"; shift
    ;;            
        --verbose|-v)
            verb='v'; shift
    ;; 
        *.${ext})
            pkg="$op"; shift
    ;;
        --help|-h)
            usage; shift
    ;;
    esac                                       
}    
 
for param in "$@"; do
    get_opt "$param"
 
    if [ "$cmd" = "i" ] && [ -n "$pkg" ]; then
        install "$pkg" && echo "Package installed successfully" || { echo "Error installing package $pkg"; exit 1; }
        unset pkg
    fi
done

case "$cmd" in
    --install|-i)
        exit
        ;;
    --create|-c)
        if [ -z "$pkg" ]; then
            echo "Missing package name"
            exit 1
        fi
      
        pkg_check "$pkg"                     || { echo $err; exit 1; }
    
        pkg_create "$pkg" $verb && echo $out || { echo $out; exit 1; }
        ;;
    --info|-I)
        . "$destdir"/info

        if [ -z "$pkg" ]; then
            make_desc
        else
            show_desc "$pkg"
        fi ;;
    *)
        echo Bye
    ;;
esac

