#!/bin/sh

export ext='rock'
export LC_ALL='C'
export LANG='C'

destdir=/home/wanderson/rockpkg
. "$destdir"/help
. "$destdir"/create
. "$destdir"/install

get_opt() {
    op="$1"
    case $op in
        --create|-c|--info|-I|--remove|-r|--help|-h)
            cmd="$op"
    ;;
        --install|-i)
            cmd="i"
    ;;
        --verbose|-v)
            verb='v'
    ;;
        *.${ext})
            pkg="$op"
    ;;
        *)
            prog="$op"
    ;;
    esac
    shift
}
 
[ -z $1 ] && { usage; exit 1; }

for param in "$@"; do
    get_opt "$param"
 
    if [ "$cmd" = "i" ] && [ -n "$pkg" ]; then
        install "$pkg" && echo "Package installed successfully" || { echo "Error installing package $pkg"; exit 1; }
        unset pkg
    fi
done

case "$cmd" in
    --install|-i)
        exit
        ;;
    --create|-c)
        [ -z "$pkg" ] && { echo "Missing package name"; exit 1; }
      
        pkg_check "$pkg"                     || { echo $err; exit 1; }
    
        pkg_create "$pkg" $verb && echo $out || { echo $out; exit 1; }
        exit 0 ;;
    --info|-I)
        . "$destdir"/info

        if [ -z "$pkg" ]; then
            make_desc
        else
            show_desc "$pkg"
        fi
        exit 0 ;;
    --remove|-r)
        [ -z "$prog" ] && { echo "Missing program"; exit 1; }
        
        . "$destdir"/remove
        cd $track
        found=false
        for f in *; do
            if echo "$f" | grep -wq "$prog"; then
                pkg_remove "$f"; found=true; break
            fi
        done
        if [ "$found" = false ]; then
            echo "Unable to locate program $prog"; exit 1;
        else            
            echo "package removed successfully"
        fi

        exit 0 ;;
    --help|-h)
        help
        exit 0 ;;
esac

